### PR TITLE
Add Homebrew cask install instructions.

### PR DESCRIPTION
**Pull request by rajiv**
Add Homebrew cask install instructions.

### CODE REVIEW

**Comment by joelekstrom** [comment]
Thanks! 👏

**Comment by joelekstrom** [comment]
@rajiv I've added a notarised version of 1.8.0, and now bumped minimum deployment target to 10.15 - is it possible to mark the cask so that users on 10.14 or older will get the 1.8.0 build and newer os's get the latest version?

Thanks for maintaining the homebrew stuff!

**Comment by rajiv** [comment]
@joelekstrom I already developed this support in rajiv/homebrew-fastmate@66ca208f56c8dc3bc2fd3383b5370e696c6d27b3 last night. Try it out!

**Comment by joelekstrom** [comment]
Awesome, thank you! 😊

**Pull request merged**
